FROM alpine:latest as prod
RUN apk update && apk add qt5-qtbase

ENV USER_NAME touchpanel
ENV USER_GROUP hipase-restricted
ENV HOME_DIR /home/${USER_NAME}

RUN addgroup -S ${USER_GROUP}
RUN adduser -S ${USER_NAME} -G ${USER_GROUP}
