FROM debian:latest as build-env

ENV BUILD_USER_NAME developer
ENV BUILD_HOME_DIR /home/${USER_NAME}

RUN apt-get update && apt-get -y install sudo apt-utils gcc g++ gdb cmake make build-essential

RUN export uid=1000 gid=1000 && \
    mkdir -p ${BUILD_HOME_DIR} && \
    echo "${BUILD_USER_NAME}:x:${uid}:${gid}:${BUILD_USER_NAME},,,:${BUILD_HOME_DIR}:/bin/bash" >> /etc/passwd && \
    echo "${BUILD_USER_NAME}:x:${uid}:" >> /etc/group && \
    echo "${BUILD_USER_NAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${BUILD_USER_NAME} && \
    chmod 0440 /etc/sudoers.d/${BUILD_USER_NAME} && \
    chown ${uid}:${gid} -R ${BUILD_HOME_DIR}

RUN apt-get install -y qt5-default qt4-dev-tools qtbase5-examples qtcreator

USER ${BUILD_USER_NAME}
WORKDIR ${BUILD_HOME_DIR}
#CMD ["qmake elasticnodes.pro && make mocables all"]
