FROM ubuntu:18.04 as build-env

ENV BUILD_USER_NAME developer
ENV BUILD_HOME_DIR /home/${BUILD_USER_NAME}

RUN apt-get update && apt-get -y install sudo apt-utils
RUN apt-get install -y gcc g++ gdb cmake make build-essential qt5-default qt4-dev-tools qtbase5-examples qtcreator

RUN mkdir -p ${BUILD_HOME_DIR}/build
WORKDIR ${BUILD_HOME_DIR}/build
COPY QtExampleApp/elasticnodes ${BUILD_HOME_DIR}/build
RUN ls -l && qmake -makefile && make && ls -l

FROM alpine:latest as ops-env
RUN apk update && apk add qt5-qtbase qt5-qtbase-x11 libc6-compat shadow

ENV USER_NAME touchpanel
ENV USER_GROUP touchpanel
ENV HOME_DIR /home/${USER_NAME}
ENV BINARY_SRC_DIR /home/developer/build

ENV ROOT_PWD hipahipa

RUN set -x \
  && addgroup -g 1000 ${USER_GROUP} \
  && adduser -u 1000 -D -S -G ${USER_GROUP} ${USER_NAME}
RUN echo "root:${ROOT_PWD}" | chpasswd

RUN mkdir -p ${HOME_DIR}
USER ${USER_NAME}
WORKDIR ${HOME_DIR}
COPY --from=build-env ${BINARY_SRC_DIR}/elasticnodes .
CMD ["./elasticnodes"]
